function exportNewRelationships_general(relationships, relationships_equations, ...
    relationships_language, inMetaNetX, n_notInMetaNetX, MNXIDs, ...
    modelIndices, indices, excelFileName, species)

labels = {'ID in manuallly-curated model',...
    'ID in draft reconstruction',...
    'reaction equation in manuallly-curated model',...
    'translated reaction equation in draft reconstruction',...
    'ID type in manually-curated model',...
    'ID type in draft reconstruction',...
    'is relationship in MetaNetx',...
    'MNXID'};

info = [relationships(indices,1), relationships(indices,2),...
    relationships_equations(indices,1), relationships_equations(indices,2), ...
    relationships_language(indices,1), relationships_language(indices,2),...
    num2cell(inMetaNetX(indices)), MNXIDs(indices)];

info2 = [labels;info];
xlswrite([excelFileName '_' species], info2)

withoutMNXIDs = find(cellfun(@isempty, MNXIDs));
indices2 = intersect(indices, withoutMNXIDs);

info = [relationships(indices2,1), relationships(indices2,2),...
    relationships_equations(indices2,1),relationships_equations(indices2,2), ...
    relationships_language(indices2,1), relationships_language(indices2,2),...
    num2cell(inMetaNetX(indices2)), MNXIDs(indices2)];

info2 = [labels;info];
xlswrite([excelFileName '_' species], info2, 'notInMNX')

xlswrite([excelFileName '_' species], [{'not in MNX'} n_notInMetaNetX], 'summary')


end